### PR TITLE
Making Obstacle move

### PR DESCRIPTION
**Pull request by chutsu**
Still in progress, but just wanted you to be in the loop of the changes I'm currently making. 

Currently still trying to parse the dynamic obstacle map file into CRoPs, but having problems passing the correct constructor arguments, because at the moment you don't use **kwargs. So I'm working through the sequence and making minor changes.

### CODE REVIEW

**Comment by chutsu** [comment]
Refactored your nasty little filter code:

```
line = filter(
    lambda s: s != "\n",
    f.readline().split(" ")
)[1:]
```

To:

```
line = [line for line in f.readline().split()[1:]]
```

in `mparse()`

:D

**Comment by chutsu** [comment]
Nearly there...

**Comment by a20r** [comment]
Nice refactoring. How long until you think it will be done?

**Comment by chutsu** [comment]
Done!

Run this: 

```
python code/test_sim.py maps/scene1.map 50 maps/scene1.obstacles
```

**Pull request closed without merging**
